export const itemsData = [
    {
        name: "Toshiba 1TB Canvio Basics Portable External Hard Drive",
        image: "https://m.media-amazon.com/images/I/71ud13duG4L._AC_SX425_.jpg",
        price: "£36.15",
        link: "https://amzn.to/3MAO04i",
        brand: "TOSHIBA",
    },
    {
        name: "Seagate Portable Drive, 1TB",
        image: "https://m.media-amazon.com/images/I/61uF7GopfcL._AC_SY879_.jpg",
        price: "£39.86",
        link: "https://amzn.to/38xRZjm",
        brand: "Seagate",
    },
    {
        name: "Seagate Expansion Portable 1 TB",
        image: "https://m.media-amazon.com/images/I/61y-1qRsFWL._AC_SX425_.jpg",
        price: "£46.78",
        link: "https://amzn.to/380dkS0",
        brand: "Seagate",
    },
    {
        name: "2021 Apple MacBook Pro (16-inch, Apple M1 Pro chip with 10‑core CPU and 16‑core GPU, 16GB RAM, 512GB SSD) - Space Grey",
        image: "https://m.media-amazon.com/images/I/61aUBxqc5PL._AC_SX679_.jpg",
        price: "£2,129.00",
        link: "https://amzn.to/3wtQjQK",
        brand: "Apple",
    },
    {
        name: "New Apple MacBook Pro with Apple M1 Chip (13-inch, 8GB RAM, 512GB SSD) - Space Grey (Latest Model)",
        image: "https://m.media-amazon.com/images/I/71an9eiBxpL._AC_SX679_.jpg",
        price: "£1,249.97",
        link: "https://amzn.to/39CDFpC",
        brand: "Apple",
    },
    {
        name: "Lenovo IdeaPad 5i 15 Inch Full HD Laptop (Intel Core i5, 8GB RAM, 256GB SSD Storage",
        image: "https://m.media-amazon.com/images/I/71Y2NpxZEiS._AC_SX425_.jpg",
        price: "£429.99",
        link: "https://amzn.to/3sIfpcj",
        brand: "Lenovo",
    },
    {
        name: "ASUS Vivobook 15 M513UA 15.6 Inch Full HD OLED Laptop, Black (AMD Ryzen 5-5500U, 8GB RAM, 512GB SSD",
        image: "https://m.media-amazon.com/images/I/61dKwnQtCvS._AC_SX425_.jpg",
        price: "£479.99",
        link: "https://amzn.to/3yIa4FY",
        brand: "ASUS",
    },
    {
        name: "2020 Apple MacBook Air Laptop: Apple M1 Chip, 13” Retina Display, 8GB RAM, 512GB SSD Storage",
        image: "https://m.media-amazon.com/images/I/71vFKBpKakL._AC_SX679_.jpg",
        price: "£1,129.97",
        link: "https://amzn.to/3NgIL9M",
        brand: "Apple",
    },
    {
        name: "ASUS TUF Gaming FX506HCB 15.6inch 144Hz Intel i5-11400H, Nvidia GeForce RTX 3050, 8GB RAM, 512GB SSD",
        image: "https://m.media-amazon.com/images/I/61oglkl45CL._AC_SX425_.jpg",
        price: "£649.99",
        link: "https://amzn.to/3MFjF4E",
        brand: "ASUS",
    },
    {
        name: "AOC Gaming 24G2U -24 Inch FHD Monitor, 144Hz, 1ms, IPS, AMD FreeSync",
        image: "https://m.media-amazon.com/images/I/71QFFU--5zL._AC_SX425_.jpg",
        price: "£159.00",
        link: "https://amzn.to/3PyiIN9",
        brand: "AOC",
    },
    {
        name: "LG Full HD Gaming Monitor 22MK400H - 22 inch, 60 Hz, 1 ms, 1920X1080 px",
        image: "https://m.media-amazon.com/images/I/51KIfWbhXwL._AC_SX425_.jpg",
        price: "£89.90",
        link: "https://amzn.to/39EJ7Ix",
        brand: "LG",
    },
    {
        name: "AOC Gaming Q27G2S - 27 Inch QHD Monitor, 165Hz, 1ms, IPS, FreeSync, Gsync Compatible",
        image: "https://m.media-amazon.com/images/I/81G3yCN5k+L._AC_SX425_.jpg",
        price: "£239.95",
        link: "https://amzn.to/3MzcieV",
        brand: "AOC",
    },
];
