export const itemsData = [
    {
        name: "Tommy Hilfiger Men's Repeat Logo Tape Joggers Thermal Trousers",
        image: "https://m.media-amazon.com/images/I/71ASc5YcazL._AC_UX679_.jpg",
        price: "£35.78 ",
        link: "https://amzn.to/3LyTBXt",
        brand: "Tommy Hilfiger",
    },
    {
        name: "Nike Mens AW77 Cuffed Fleece Lined Joggers",
        image: "https://m.media-amazon.com/images/I/61sGfcsYuNL._AC_UY741_.jpg",
        price: "£32.99",
        link: "https://amzn.to/3wDK37V",
        brand: "Nike",
    },
    {
        name: "Tommy Hilfiger Men's Rn Tee Ss T-shirt, Blue (Navy Blazer 416)",
        image: "https://m.media-amazon.com/images/I/71QWWapKiZL._AC_UX569_.jpg",
        price: "£24.00",
        link: "https://amzn.to/3G1O0aY",
        brand: "Tommy Hilfiger",
    },
    {
        name: "Tommy Hilfiger Men's Rn Tee Ss T-shirt, Blue (Navy Blazer 416)",
        image: "https://m.media-amazon.com/images/I/91yluegR-tS._AC_SX569._SX._UX._SY._UY_.jpg",
        price: "£25.00",
        link: "https://amzn.to/3wwTkjo",
        brand: "Tommy Hilfiger",
    },
    {
        name: "Polo Ralph Lauren - Mens Small Pony Crew Neck Cotton Jersey T-Shirt)",
        image: "https://m.media-amazon.com/images/I/614w9ARdBgL._AC_UX679_.jpg",
        price: "£61.15",
        link: "https://amzn.to/3sIi9GT",
        brand: "Polo Ralph Lauren",
    },
    {
        name: "Ralph Lauren Men's French Rib Half Zip Pullover",
        image: "https://m.media-amazon.com/images/I/51aO4zxwfGL._AC_UX569_.jpg",
        price: "£159.00",
        link: "https://amzn.to/3sLRnNI",
        brand: "Polo Ralph Lauren",
    },
    {
        name: "Ralph Lauren Polo Shirt Men's Classic Fit Short Sleeve",
        image: "https://m.media-amazon.com/images/I/51LH4uQzZYL._AC_UX679_.jpg",
        price: "£95.00",
        link: "https://amzn.to/3MA8cmM",
        brand: "Ralph Lauren",
    },
    {
        name: "BOSS Mens Gordon Regular-fit Shirt in Cotton Twill",
        image: "https://m.media-amazon.com/images/I/51wCbI+-9eL._AC_UY741_.jpg",
        price: "£99.00",
        link: "https://amzn.to/3G4qxG4",
        brand: "BOSS",
    },
    {
        name: "Ralph Lauren Men's Slim Fit Oxford Shirt (Large, Blue)",
        image: "https://m.media-amazon.com/images/I/611hLjstSNL._AC_UX569_.jpg",
        price: "£130.00",
        link: "https://amzn.to/3G2at7R",
        brand: "Ralph Lauren",
    },
    {
        name: "Polo Ralph Lauren Mens Classic Fit Oxford Longsleeve Buttondown Shirt",
        image: "https://m.media-amazon.com/images/I/41tfzNov-kL._AC_UX679_.jpg",
        price: "£95.88",
        link: "https://amzn.to/3MADFVM",
        brand: "Ralph Lauren",
    },
    {
        name: "Ralph Lauren Men's Pima Cotton Crew Neck Jumper",
        image: "https://m.media-amazon.com/images/I/71Ki4ZhEg5L._AC_UY741_.jpg",
        price: "£119.00",
        link: "https://amzn.to/3lruGdG",
        brand: "Ralph Lauren",
    },
    {
        name: "Ralph Lauren Polo Half Zip Cable Knit Jumper Mens",
        image: "https://m.media-amazon.com/images/I/71vtV+dtWFL._AC_SY741._SX._UX._SY._UY_.jpg",
        price: "£151.89",
        link: "https://amzn.to/3wGkULn",
        brand: "Ralph Lauren",
    },
    {
        name: "Ralph Lauren Polo Half Zip Cable Knit Jumper Mens",
        image: "https://m.media-amazon.com/images/I/811E6aCnBpL._AC_SY741._SX._UX._SY._UY_.jpg",
        price: "£150.90",
        link: "https://amzn.to/3wuzbuq",
        brand: "Ralph Lauren",
    },
    {
        name: "Polo Ralph Lauren Men's Classic Fleece Full Zip Hoodie, Navy (White Pony)",
        image: "https://m.media-amazon.com/images/I/81MGMQilscL._AC_UX569_.jpg",
        price: "£120.00",
        link: "https://amzn.to/3LwGlT9",
        brand: "Ralph Lauren",
    },
];
