export const itemsData = [
    {
        name: "air nike one",
        image: "imagesfolder",
        price: 90,
        description: "Air Nike Jordan One 1997 first realease brand MJ",
    },
    {
        name: "air nike Jordan",
        image: "imagesfolder",
        price: 120,
        description: "Air Nike Jordan 1997, special edition",
    },
    {
        name: "air nike",
        image: "imagesfolder",
        price: 80,
        description: "Air Nike Jordan 1997",
    },
    {
        name: "air nike one",
        image: "imagesfolder",
        price: 90,
        description: "Air Nike Jordan One 1997 first realease brand MJ",
    },
    {
        name: "air nike Jordan",
        image: "imagesfolder",
        price: 120,
        description: "Air Nike Jordan 1997, special edition",
    },
    {
        name: "air nike",
        image: "imagesfolder",
        price: 80,
        description: "Air Nike Jordan 1997",
    },
    {
        name: "air nike one",
        image: "imagesfolder",
        price: 90,
        description: "Air Nike Jordan One 1997 first realease brand MJ",
    },
    {
        name: "air nike Jordan",
        image: "imagesfolder",
        price: 120,
        description: "Air Nike Jordan 1997, special edition",
    },
    {
        name: "air nike",
        image: "imagesfolder",
        price: 80,
        description: "Air Nike Jordan 1997",
    },
    {
        name: "air nike one",
        image: "imagesfolder",
        price: 90,
        description: "Air Nike Jordan One 1997 first realease brand MJ",
    },
    {
        name: "air nike Jordan",
        image: "imagesfolder",
        price: 120,
        description: "Air Nike Jordan 1997, special edition",
    },
    {
        name: "air nike",
        image: "imagesfolder",
        price: 80,
        description: "Air Nike Jordan 1997",
    },
    {
        name: "air nike one",
        image: "imagesfolder",
        price: 90,
        description: "Air Nike Jordan One 1997 first realease brand MJ",
    },
    {
        name: "air nike Jordan",
        image: "imagesfolder",
        price: 120,
        description: "Air Nike Jordan 1997, special edition",
    },
    {
        name: "air nike",
        image: "imagesfolder",
        price: 80,
        description: "Air Nike Jordan 1997",
    },
    {
        name: "air nike one",
        image: "imagesfolder",
        price: 90,
        description: "Air Nike Jordan One 1997 first realease brand MJ",
    },
    {
        name: "air nike Jordan",
        image: "imagesfolder",
        price: 120,
        description: "Air Nike Jordan 1997, special edition",
    },
    {
        name: "air nike",
        image: "imagesfolder",
        price: 80,
        description: "Air Nike Jordan 1997",
    },
];
