export const itemsData = [
    {
        name: "NIKE Men's Air Jordan 1",
        image: "https://m.media-amazon.com/images/I/71SKNAg3KcL._AC_SY695._SX._UX._SY._UY_.jpg",
        price: "£382.85",
        link: "https://amzn.to/3Mxa3Zr",
        brand: "NIKE",
    },
    {
        name: "NIKE Men's Air Jordan 1",
        image: "https://m.media-amazon.com/images/I/719CyRjRMHL._AC_UX575_.jpg",
        price: "£365.84",
        link: "https://amzn.to/3aclYxB",
        brand: "NIKE",
    },
    {
        name: "NIKE Men's Air Jordan 1",
        image: "https://m.media-amazon.com/images/I/61GNW4P2O2L._AC_SX575._SX._UX._SY._UY_.jpg",
        price: "£340.31",
        link: "https://amzn.to/3Pxs9MM",
        brand: "NIKE",
    },
    {
        name: "NIKE Men's Air Jordan 1",
        image: "https://m.media-amazon.com/images/I/61MGm5gT1JL._AC_SX575._SX._UX._SY._UY_.jpg",
        price: "£382.56",
        link: "https://amzn.to/39CsugD",
        brand: "NIKE",
    },
    {
        name: "NIKE Men's Air Jordan 1",
        image: "https://m.media-amazon.com/images/I/71q34YSE8GL._AC_SX575._SX._UX._SY._UY_.jpg",
        price: "£323.30",
        link: "https://amzn.to/3NlBN3l",
        brand: "NIKE",
    },
    {
        name: "NIKE Men's Air Jordan 1",
        image: "https://m.media-amazon.com/images/I/71A1g5Vu4eL._AC_SX575._SX._UX._SY._UY_.jpg",
        price: "£168.16",
        link: "https://amzn.to/3wFPqU8",
        brand: "NIKE",
    },
    {
        name: "NIKE Men's Air Jordan 1",
        image: "https://m.media-amazon.com/images/I/61nmeKiYCjL._AC_SY575._SX._UX._SY._UY_.jpg",
        price: "£349.00",
        link: "https://amzn.to/3NkZNUc",
        brand: "NIKE",
    },
    {
        name: "NIKE Men's Air Jordan 1",
        image: "https://m.media-amazon.com/images/I/711CxBvx3FL._AC_SX575._SX._UX._SY._UY_.jpg",
        price: "£425.39",
        link: "https://amzn.to/3MvzuL0",
        brand: "NIKE",
    },
    {
        name: "adidas Jeans Grey Blue",
        image: "https://m.media-amazon.com/images/I/71P+qaj+J+L._AC_UX625_.jpg",
        price: "£69.99",
        link: "https://amzn.to/3G8eyYc",
        brand: "ADIDAS",
    },
    {
        name: "adidas Jeans Grey Blue",
        image: "https://m.media-amazon.com/images/I/61i8YMs0WlL._AC_SY625._SX._UX._SY._UY_.jpg",
        price: "£59.99",
        link: "https://amzn.to/3NumTId",
        brand: "ADIDAS",
    },
    {
        name: "adidas Men's Zx 750'",
        image: "https://m.media-amazon.com/images/I/71o8INn1vcL._AC_UX575_.jpg",
        price: "£67.99",
        link: "https://amzn.to/39Bb5Fo",
        brand: "ADIDAS",
    },
    {
        name: "adidas Men's Zx 750'",
        image: "https://m.media-amazon.com/images/I/81FDT-OS76L._AC_SX575._SX._UX._SY._UY_.jpg",
        price: "£67.50",
        link: "https://amzn.to/3G1z8cr",
        brand: "ADIDAS",
    },
    {
        name: "adidas Samba",
        image: "https://m.media-amazon.com/images/I/71+gH-mgMrL._AC_UY575_.jpg",
        price: "£59.19",
        link: "https://amzn.to/3Lt0MAn",
        brand: "ADIDAS",
    },

    {
        name: "adidas Powerlift.3.1",
        image: "https://m.media-amazon.com/images/I/51ja0Ye6A4L._AC_UX695_.jpg",
        price: "£99.95",
        link: "https://amzn.to/3wJowuS",
        brand: "ADIDAS",
    },
    {
        name: "adidas Gazelle",
        image: "https://m.media-amazon.com/images/I/41FHizDfnFL._AC_UY625_.jpg",
        price: "£120.54",
        link: "https://amzn.to/3LvU2l4",
        brand: "ADIDAS",
    },
];
